"""Add GroupBuy and GroupBuyParticipant tables

Revision ID: 06281c22fb55
Revises: 5cfacd676d31
Create Date: 2025-03-14 19:19:59.229977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06281c22fb55'
down_revision = '5cfacd676d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_buys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Float(), nullable=False),
    sa.Column('min_participants', sa.Integer(), nullable=False),
    sa.Column('current_participants', sa.Integer(), nullable=True),
    sa.Column('unique_link', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unique_link')
    )
    op.create_table('group_buy_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_buy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_buy_id'], ['group_buys.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_buy_participants')
    op.drop_table('group_buys')
    # ### end Alembic commands ###
