"""Detecting changes

Revision ID: 1a85ddbfaf36
Revises: 45496aaeaedb
Create Date: 2025-03-08 17:14:03.356911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a85ddbfaf36'
down_revision = '45496aaeaedb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###
