"""Detecting changes

Revision ID: 201639cfe699
Revises: 1a85ddbfaf36
Create Date: 2025-03-08 17:18:05.074116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '201639cfe699'
down_revision = '1a85ddbfaf36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
