"""Change uniqueLink from Boolean to String in Product model

Revision ID: 244965deec65
Revises: 4605249bc635
Create Date: 2025-03-28 15:59:45.444364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '244965deec65'
down_revision = '4605249bc635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('uniqueLink',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('uniqueLink',
               existing_type=sa.String(length=50),
               type_=sa.BOOLEAN(),
               existing_nullable=True)

    # ### end Alembic commands ###
