"""update

Revision ID: 329701a5de7c
Revises: 24403d3475c8
Create Date: 2025-03-05 17:58:19.924750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '329701a5de7c'
down_revision = '24403d3475c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
