"""Detecting changes

Revision ID: 45496aaeaedb
Revises: 9fb6ab733964
Create Date: 2025-03-08 17:04:40.399888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45496aaeaedb'
down_revision = '9fb6ab733964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
