"""updated product mdoel

Revision ID: 4605249bc635
Revises: dbd0524124e2
Create Date: 2025-03-28 15:57:39.438498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4605249bc635'
down_revision = 'dbd0524124e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uniqueLink', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_groupbuy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_groupbuy', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('uniqueLink')

    # ### end Alembic commands ###
