"""deleted column

Revision ID: 5526c36d1eb3
Revises: 74f2c7bc4878
Create Date: 2025-03-10 16:56:49.002053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5526c36d1eb3'
down_revision = '74f2c7bc4878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.drop_column('dummy_col')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_col', sa.VARCHAR(length=18), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
