"""Update

Revision ID: 5cfacd676d31
Revises: 5526c36d1eb3
Create Date: 2025-03-10 21:07:21.073526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfacd676d31'
down_revision = '5526c36d1eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verify', sa.Boolean(), nullable=True))
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
        batch_op.drop_column('email_verify')

    # ### end Alembic commands ###
