"""Added daily login bonus

Revision ID: 6094923561f2
Revises: a1075ac93347
Create Date: 2025-03-20 13:40:42.188263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6094923561f2'
down_revision = 'a1075ac93347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('login_streak', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.drop_column('login_streak')
        batch_op.drop_column('last_login_date')

    # ### end Alembic commands ###
