"""Detecting changes

Revision ID: 74f2c7bc4878
Revises: d2ac461b0603
Create Date: 2025-03-10 16:55:24.769005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f2c7bc4878'
down_revision = 'd2ac461b0603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy_col', sa.String(length=18), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.drop_column('dummy_col')

    # ### end Alembic commands ###
