"""Detecting changes

Revision ID: 990150974ec5
Revises: 
Create Date: 2025-03-08 16:39:38.485595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '990150974ec5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###
