"""updated user table to include credit system

Revision ID: a1075ac93347
Revises: 06281c22fb55
Create Date: 2025-03-18 17:42:19.521167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1075ac93347'
down_revision = '06281c22fb55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credits', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.drop_column('credits')

    # ### end Alembic commands ###
