"""Force detection

Revision ID: b2f8cbe1d1c6
Revises: 201639cfe699
Create Date: 2025-03-08 17:28:27.307903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2f8cbe1d1c6'
down_revision = '201639cfe699'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###
