"""Altered user db

Revision ID: d2ac461b0603
Revises: 0af6500ad746
Create Date: 2025-03-09 18:06:42.793393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2ac461b0603'
down_revision = '0af6500ad746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.drop_column('temp_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('_user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_column', sa.VARCHAR(length=10), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
